### ISSUE TITLE
Broken link to demo bagfile

### ISSUE THREAD

**Issue by ruffsl** [googlecartographer/cartographer_fetch#1]
In the docs, [index.rst](https://github.com/googlecartographer/cartographer_fetch/blob/1c6fd55/docs/source/index.rst), there is a refrince to a demo bagfile for the fetch.
However the link apears to be currently broken:
https://storage.googleapis.com/cartographer-public-data/bags/fetch/cartographer_freight_simulation_demo.bag

**Comment by damonkohler** [comment]
Fixed, thanks.
