### ISSUE TITLE
Enable IMU?

### ISSUE THREAD

**Issue by ruffsl** [googlecartographer/cartographer_fetch#2]
I see use of the IMU has been left disabled. Are there any current blockers, or it just a matter of testing it? [freight.lua#L38-L39](https://github.com/googlecartographer/cartographer_fetch/blob/1c6fd552ecdf5921b22d853436296187d156836e/cartographer_fetch/configuration_files/freight.lua#L38-L39)

I'd be happy help test it. Enabling it just quickly I didn't notice anything drastically different, but I do see the node is subscribed to the `/imu` topic, and should be being used: [sensor_bridge.cc#L71](https://github.com/googlecartographer/cartographer_ros/blob/33271f029093f77df83c0611b1688f781a71cb92/cartographer_ros/cartographer_ros/sensor_bridge.cc#L71)

**Comment by damonkohler** [comment]
It's just a matter of testing it out. I only have access to the simulated robot where IMU isn't supported.

If you'd like to file a PR to enable it, please ensure there's also a configuration for the simulated robot.
